version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
    ignore:
      # Ignore updates to git-based dependencies
      - dependency-name: "git+https://github.com/fireflyprotocol/bluefin-client-python-sui.git"
      - dependency-name: "git+https://github.com/fireflyprotocol/bluefin-v2-client-python.git"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/infrastructure/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
      include: "scope" 