version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
      - ./analysis:/app/analysis
      - ./.env:/app/.env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - BLUEFIN_PRIVATE_KEY=${BLUEFIN_PRIVATE_KEY}
      - BLUEFIN_NETWORK=${BLUEFIN_NETWORK:-MAINNET}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3.7-sonnet}
      - CLAUDE_MAX_TOKENS=${CLAUDE_MAX_TOKENS:-8000}
      - CLAUDE_TEMPERATURE=${CLAUDE_TEMPERATURE:-0.2}
      - CLAUDE_REQUESTS_PER_MINUTE=${CLAUDE_REQUESTS_PER_MINUTE:-50}
      - CLAUDE_INPUT_TOKENS_PER_MINUTE=${CLAUDE_INPUT_TOKENS_PER_MINUTE:-20000}
      - CLAUDE_OUTPUT_TOKENS_PER_MINUTE=${CLAUDE_OUTPUT_TOKENS_PER_MINUTE:-8000}
    restart: unless-stopped
    depends_on:
      - ngrok
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 app:app

  trader:
    build: .
    volumes:
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
      - ./analysis:/app/analysis
      - ./.env:/app/.env
    environment:
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - BLUEFIN_PRIVATE_KEY=${BLUEFIN_PRIVATE_KEY}
      - BLUEFIN_NETWORK=${BLUEFIN_NETWORK:-MAINNET}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3.7-sonnet}
      - CLAUDE_MAX_TOKENS=${CLAUDE_MAX_TOKENS:-8000}
      - CLAUDE_TEMPERATURE=${CLAUDE_TEMPERATURE:-0.2}
      - CLAUDE_REQUESTS_PER_MINUTE=${CLAUDE_REQUESTS_PER_MINUTE:-50}
      - CLAUDE_INPUT_TOKENS_PER_MINUTE=${CLAUDE_INPUT_TOKENS_PER_MINUTE:-20000}
      - CLAUDE_OUTPUT_TOKENS_PER_MINUTE=${CLAUDE_OUTPUT_TOKENS_PER_MINUTE:-8000}
    restart: unless-stopped
    depends_on:
      - web
    command: python agent.py

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    command: http --domain=${NGROK_DOMAIN:-} web:5000 