version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "${NGINX_PORT:-8080}:80"
    restart: on-failure
    networks:
      - perplexity-network
    depends_on:
      - webhook
      - websocket
      - agent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
  
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    image: perplexitytrader-webhook:${TAG:-latest}
    volumes:
      - ../../alerts:/app/alerts:ro
      - ../../logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - WEBHOOK_PORT=${WEBHOOK_PORT:-5004}
      - WEBHOOK_HOST=${WEBHOOK_HOST:-0.0.0.0}
      - USE_HOOKDECK=${USE_HOOKDECK:-false}
      - PYTHONUNBUFFERED=1
    restart: on-failure
    ports:
      - "${WEBHOOK_PORT:-5004}:${WEBHOOK_PORT:-5004}"
    networks:
      - perplexity-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEBHOOK_PORT:-5004}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    command: ["simple_webhook.py"]
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    image: perplexitytrader-websocket:${TAG:-latest}
    volumes:
      - ../../logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - SOCKET_PORT=${SOCKET_PORT:-5008}
      - WEBSOCKET_PATH=${WEBSOCKET_PATH:-/socket.io}
      - PYTHONUNBUFFERED=1
    restart: on-failure
    ports:
      - "${SOCKET_PORT:-5008}:${SOCKET_PORT:-5008}"
    networks:
      - perplexity-network
    depends_on:
      - webhook
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SOCKET_PORT:-5008}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    command: ["simple_websocket.py"]
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    image: perplexitytrader-agent:latest
    volumes:
      - ../../logs:/app/logs
      - ../../alerts:/app/alerts:ro
      - ../../core:/app/core:ro
      - ../../analysis:/app/analysis
      - ./.env:/app/.env:ro
    environment:
      - FLASK_APP_PORT=${FLASK_APP_PORT:-5003}
      - PYTHONUNBUFFERED=1
      - MOCK_TRADING=${MOCK_TRADING:-true}
    restart: on-failure
    ports:
      - "${FLASK_APP_PORT:-5003}:${FLASK_APP_PORT:-5003}"
    depends_on:
      - webhook
      - websocket
    networks:
      - perplexity-network
    shm_size: 2gb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLASK_APP_PORT:-5003}/health || exit 1"]
      interval: 45s
      timeout: 15s
      retries: 3
      start_period: 30s
    command: ["simple_agent.py"]
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

networks:
  perplexity-network:
    driver: bridge 